BOARD_INSUFFICIENT_MEMORY := \
    airfy-beacon \
    chronos \
    msb-430 \
    msb-430h \
    nrf51dongle \
    nrf6310 \
    nucleo-f103 \
    nucleo-f334 \
    pca10000 \
    pca10005 \
    spark-core \
    stm32f0discovery \
    telosb \
    weio \
    wsn430-v1_3b \
    wsn430-v1_4 \
    yunjia-nrf51822 \
    z1 \
    #
